### ISSUE TITLE
Add `await*` as alias of `await.all`? (Also matches `yield*`) 

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-await.ops#10]

**Comment by ljharb** [comment]
No, for a few reasons:
 - it doesn’t match yield* in semantics, whatsoever
 - a big part of the reason await* was removed from async/await is that it only handled “all”
 - the * conveys no meaning here, and is confusing (it’s confusing in yield* too, but that ship has sailed)

**Comment by Jack-Works** [comment]
> it doesn’t match yield\* in semantics, whatsoever

yield\* expr = yield all things in the expr

await \* expr = await all things in the expr

I think there is symmetry.

**Comment by ExE-Boss** [comment]
Well, `yield*` at least has some symmetry with `function*`, but `async function*` and `await.all` don’t actually have any overlap, as `Promise` statics don’t accept async iterables: <https://github.com/tc39/ecma262/issues/1909>.

You could define `await* foo` as being `await AsyncIterator.prototype.toArray.call(foo[Symbol.asyncIterator]())`, which would match `yield*` semantics, but that would probably be confusing, and you can always use the `toArray` iterator helper method.
