### ISSUE TITLE
Is it possible to use `await` on arrays implicitly?

### ISSUE THREAD

**Issue by junaga** [tc39/proposal-await.ops#21]
```js
await download(username)
```
and
```js
await users.map((user) => download(user))
```
Both just work.

**Comment by ljharb** [comment]
No, it’s not. There’s nothing preventing an array from being thenable, and current code relies on arrays NOT being awaitable.

**Comment by junaga** [comment]
I want to vote on arrays being awaitable, is there another proposal?

**Comment by ljharb** [comment]
Nothing is done in the language via voting, and since it would break code, it can never happen, period.

**Comment by junaga** [comment]
This is the part I don't understand, sorry if my issue/question is stupid.

But why would it be a breaking change?

**Comment by ljharb** [comment]
```js
async function check() {
  const arr = [Promise.resolve(1), Promise.resolve(2)];
  const promises = await arr;

  return promises === arr && promises[0] !== 1 && promises[1] !== 2;
}

check() // Promise for `true`
```

This code is contrived, of course, but your change would break it. Code on the web is likely depending on awaiting an array producing the same unchanged array, and we can’t ever break the web.

This is all separate from whether your change is *desirable* or not - to me, implicit is always worse than explicit, so i would object to it even if it were viable.

**Comment by junaga** [comment]
> No, it’s not. There’s nothing preventing an array from being thenable, and current code relies on arrays NOT being awaitable.

Sorry again to bother you.
But I don't mean to make Arrays `then`able. The prototype should be left as is.
My Idea was that the `await` statement implicitly wraps the array (maybe other iterables too) with `Promise.all` initially before making any calls.

I understand now that it would be a breaking change. Because non Promise references can be used with `await`. Expected to return the object unaltered.

Sorry for my novice question. I hope the proposal gets through in some kind. have a nice day 😊
