### ISSUE TITLE
It's a bit strange to have an uppercase letter (await.allSettled) in an operator

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-await.ops#5]

**Comment by ljharb** [comment]
It's a metaproperty - `await` is the operator. You can already have `super.SCREAMING_METHOD_NAME()`, for example.

**Comment by Jack-Works** [comment]
Meta property is a property. But this is a unary operator 🤔

**Comment by Alexsey** [comment]
`new` is a unary operator and `new.target` is a metaproperty that we already have for years

**Comment by hax** [comment]
I guess consistency with method names on `Promise` have the high priority 🤓

**Comment by ljharb** [comment]
Given that consistency is the priority here, and that "operators are all lowercase" is not an intentional axiom, just a convention, I think this can be closed.
