### ISSUE TITLE
Syntax ambiguity in top-level await

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-await.ops#7]
await.all [arr]

**Comment by ljharb** [comment]
What’s the ambiguity?

**Comment by Jack-Works** [comment]
> What’s the ambiguity?

It can also mean a property access in non-async context.

await.all [x]
variable.property [index]

**Comment by ljharb** [comment]
Just like TLA has a NLT restriction, id expect this one to as well. It doesn’t seem like a conflict to me.

**Comment by ljharb** [comment]
ah, i see, you mean because of the array literal. definitely worth considering before stage 2.

**Comment by ljharb** [comment]
We could also do `await all x` etc.

**Comment by chicoxyzzy** [comment]
`await all [0]` is also ambiguous. `await#all [0]`?

**Comment by ljharb** [comment]
@chicoxyzzy how is that ambiguous? `await all <anything>` is a syntax error currently.

**Comment by chicoxyzzy** [comment]
`await object[property]` is legal, so `await all[0]` is legal too

**Comment by Jack-Works** [comment]
Or maybe ban it in top-level await? It's better to keep the visual connection with meta property (maybe)

**Comment by chicoxyzzy** [comment]
@Jack-Works IMO it could be confusing that one can do `await Promise.all(array)` on top level, but can't do `await.all array`, when, in the same time, the latter is valid inside of async functions

**Comment by ljharb** [comment]
(as @chicoxyzzy schooled me on) `await all[0]` would be legal in any context, so i don't think TLA would make a difference there.

**Comment by hax** [comment]
If I understand correctly `await.all[x]` doesn't have ambiguity , because TLA only valid in module and `await` is a reserved word in module. (It's a problem of TLA --- programmers will ask why we can't use TLA in scripts, but it's not the issue of this proposal.)

But the point may be, up to now we treat `keyword.x` as meta property which returns first-class values, this proposal actually make `await.all` as operator not meta property.

**Comment by ljharb** [comment]
There's still `async function`s in Scripts, in which `await.all[0]` is still a concern.

You're right that `keyword.something` is currently only used as a metaproperty, like `super.methodName` or `import.meta`, but that doesn't preclude us expanding it to be an operator too :-)

**Comment by Jack-Works** [comment]
In non strict mode async function, await is still a keyword so we are safe

**Comment by hax** [comment]
> expanding it to be an operator

If we expand the usage, I'll expect we adopt it as a general mechanism, for example, maybe `try.using` instead of `try using` in explicit resource management proposal.  😁

**Comment by ljharb** [comment]
That would need to be argued in that proposal - regardless, just because this proposal has a meta property operator doesn’t mean every other two word construct should be a meta property.

**Comment by hax** [comment]
I really hope increase consistency between proposals. (It seems we never have two sequential word keyword before? )

And maybe `import.json x from '...'` instead of `import x from '...' with { type: "json" }` which is very lengthy.

**Comment by ljharb** [comment]
Again, that would have to be argued in the relevant proposal; however, the intention there is to allow for additional keys, so `import.json` is likely a nonstarter.

**Comment by hax** [comment]
Yeah, pls mark my comments as off topic... but it's a meta issue which cross the proposals, and i don't know which is the right place to discuss such things.

**Comment by ljharb** [comment]
I don’t think it is - there’s many forms of operators, and “meta properties can be an operator” doesn’t imo impose any consistency requirements on any other operator or syntax.

**Comment by hax** [comment]
@ljharb Whether an issue is an meta issue is already an meta issue 🤪

**Comment by Jack-Works** [comment]
as @hax says, `await` in the module is a reversed word so there is no syntax ambiguity.

The only problem is `await.all[0]` could mean different things in script and module, but there is nothing ambiguous. Can I think we're safe at this problem?

**Comment by ljharb** [comment]
Yes, i think so, because even in a Script, inside an async function there’s no ambiguity.
