### ISSUE TITLE
Support in "for of" syntax?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-await.ops#9]
For example:

for await.all (const x of q) { block }

Loosely equals to 

await Promise.all([...q].map(async x => { block })

**Comment by ljharb** [comment]
That seems like it should be a different proposal.

**Comment by Jack-Works** [comment]
they share the same new syntax `await.op`

**Comment by ljharb** [comment]
That is true - but there's no API combinators for async iteration, and this proposal is "syntax for the Promise combinators" to me.

**Comment by hax** [comment]
If there was `for await.all ... of`, what was the semantic of `for await.allSettled ... of` ?

**Comment by Jack-Works** [comment]
not intend to add it in this proposal cause the semantics will be super complex

**Comment by Jack-Works** [comment]
```typescript
async function x(y: string[]) {
    for await (const result of y.map((x) => fetch(x))) {
        result
    }
}
```

**Comment by Jack-Works** [comment]
In the last incubator call, I found out that what I really care about is improving concurrent iteration.

Today:

```js
const response = await Promise.all(
    data.map(
        async item => 
            (await fetch(new URL(item, bsae))).text()
    )
)
```

With the current proposal:

```js
const response = await.all data.map(
    async item => 
        (await fetch(new URL(item, bsae))).text()
)
```

What I really want is:

```js
const response = []
for (const item of data) with #concurrent {
    const res = await fetch(new URL(item, bsae))
    response.push(await res.text())
}
```

I think about this a little bit and got some brief ideas about this:

1. Must be opt-in concurrency
2. Maybe no `break` or `return` in it
3. Might be able to have maximum concurrency limit (e.g. `for (const item of data) with #concurrent({max: 5})`)
4. Might be able to let developer specify a "scheduler" to control the concurrency (e.g. `for (const i of b) with EXPRESSION {}`)

**Comment by ljharb** [comment]
I don't mind something like this existing (nothing with `with` or `#`, i think), but I don't personally want that at all. I never use loops in my code, and have no interest whatsoever in anything that makes looping better. I want things that make Promise composition better, specifically around the combinators.

**Comment by Jack-Works** [comment]
The syntax is not important in my idea above, it can be changed to a better form.

But `for` loop is a basic control flow in the language, and as you can see in my example above, the `for of` way is easier to read and write than the `map` version.

Another important point is that `for of` is easier to debug than the `map` (which is a important part of the developer experience).

```js
{
    let x = 1
    for (const y of [1]) { debugger }
}
```

At the `debugger` point, `x` is 1

```js
{
    let x = 1
    ;[1].map(y => {debugger})
}
```

At the `debugger` point, x is `Uncaught ReferenceError: x is not defined` because it is not "captured" by the map callback function lexically and get optimized out of the scope.
I know it is not a problem of the language but the engine, but it's actually affecting my choice on `for of` with `map`.

**Comment by hax** [comment]
> I never use loops in my code

@ljharb I'm not sure I understand this point. I think in many cases we can use `map/forEach` or similar methods, but u always need `for-of` for iterable, don't we?

**Comment by ljharb** [comment]
@Jack-Works i don't agree; i find loops always to be harder to read and write than an iteration-based version.

@hax personally? no, i never ever do.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/100177116-5d845a00-2f0c-11eb-8e2a-8f5af8cf58c4.png)

I'm still thinking of this. Maybe `await.ops` isn't powerful enough to add new syntax for it, I really care about the last case in the picture.

**Comment by ljharb** [comment]
@Jack-Works there's 4 in a grid, which do you mean by "last"?

Personally, I think `await.all` is the most compelling, merely because it's equally alluring as `await` - which is critical, because at the moment, `await` is an attractive nuisance, and too easy to use in a way that makes one's code unnecessarily sequential.

For consistency, it seems strange to omit the others.

**Comment by Jack-Works** [comment]
@ljharb I'm meaning the right-bottom one.

So if we choose the current syntax and the semantics (no changes or propose to change recently) when should we try to push this to stage 2?

**Comment by ljharb** [comment]
I'm not sure how to proceed. I think syntax is warranted, for the existing proposal as-is, but not everyone seems to agree. I think it's worth an incubator call with those who have concerns before trying to figure out next steps.

**Comment by dead-claudia** [comment]
@Jack-Works @ljharb Have you all considered `for all`/`for allSettled`/`for race`/`for any`? That might work better, and it'd also by side effect punt the question of `for await`.

To borrow @Jack-Works' example:

```
const response = []
for all (const item of data) {
    const res = await fetch(new URL(item, base))
    response.push(await res.text())
}
```

Of course, that's not a great example (I'd still use `.map` there), but one could see it useful for things that *don't* use their results after. (I don't see the value of this proposal if it continues the preference towards actually *returning* things.)

**Comment by ljharb** [comment]
`for all` without the word `await` or `async` would imo be *very* confusing - it would suggest semantics that have nothing to do with promises.

**Comment by dead-claudia** [comment]
I agree, though it's still kind of a stab in the dark. Maybe `await for all` could work?

**Comment by dead-claudia** [comment]
Also, that was...surprisingly fast of a response for a non-@. (I hadn't even submitted the edit to @ you before you responded.)

**Comment by ljharb** [comment]
Given the high bar for syntax, and this proposal's stated motivation at stage 1 ("To simplify the usage of a set of Promises"), I think that this is solidly out of scope for this proposal.
